language: go

go:
  - 1.13.x

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

script:
  - go test ./... -v -covermode=count -coverprofile=coverage.out
  - cat coverage.out | grep -v "stegify.go" > cover.out
  - goveralls -coverprofile=cover.out -service=travis-ci
  - golangci-lint run
  
  - CGO_ENABLED=0 GOARCH=386 GOOS=linux go build -o out/stegify_linux_i686 .
  - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o out/stegify_linux_x86-64 .
  - GOARCH=amd64 GOOS=darwin go build -o out/stegify_osx .
  - GOARCH=386 GOOS=windows go build -o out/stegify_win32.exe .
  - GOARCH=amd64 GOOS=windows go build -o out/stegify_win64.exe .
  
deploy:
  provider: releases
  api_key: 
    secure: "bP3tGzqpdYeVUw+9cnJvAPDSuN/+XrC9nUs1kQ7MUSHr+wkFwIFa1iRAseclr70Eika5SQaz7ehEINrJYxs4K3N/T9wpNOw0oO2+AFYfE2I088Ew2NlrMGxBvPy3pJDzY5u15wS+19r17GbU1mu+p4JAx47C7FfHXOMOZQ23vbDmOFlp7pTgjHm623W4ii7cYnDfCLiYZ3Nb5bK3ImfYdg2B80JqCRr1DVX5HqzRNJXEKOAyegMst0GmVgpbh9+3W/RrQyC7Um/tzmlVww9TXPGN9RDqMQ8N9k/kbj3NG7BPSVLVw2mWbJVuhWpBw6e+SFb5shgkWYIngphitalqkFJ4EZlvFLoO5/WuZ98hfe1h2P8dSpZ7olqlM2j0yhMJRzNRbBXQU/b+sSxDZoeg0rN4EDagJ3DX5fdWpb79oo/L3mUZvepZvGYLI79Hx233Q0T3CUjK9vT5f3mcy1mpYGxW3Ial3Q1Uso13+QJjlh0iB+SV00ZgvKcSxp/lpaHzNPqp4/srHfwSx/UQzN6d9duOJvTPsKC4EJ8IDx8iCeXvBZclkUGzu3WcZaoz4HYq1Uvl2aRWd2kbNzwCYBok+uTqQoxOf3aqk5/tzikQdGRrUr5OqVEVYnE41SZeJn01NANch0V1SC6if8WIjGWvtzgDdDWnKwQAIKEn0SiXpAQ="
  file_glob: true
  file: out/*
  skip_cleanup: true
  on:
    tags: true
